version: '2.1'
services:
  soul_admin:
    build: ../soul-admin/.
    image: "soul/soul-admin"
    container_name: soul_admin
    hostname: soul_admin
    restart: always
    ports:
      - "9095:9095"
    networks:
      - soul
  soul_bootstrap:
    build: ../soul-bootstrap/.
    image: "soul/soul-bootstrap"
    container_name: soul_bootstrap
    restart: always
    hostname: soul_bootstrap
    ports:
      - "9195:9195"
    depends_on:
      - soul_admin
    networks:
      - soul
networks:
   soul:
